###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: localhost
  gather_facts: false

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault
    - ../group_vars/backups

  environment:
    - "{{ env }}"

  tasks:
    - include_tasks: includes/find_ucp.yml ping_servers="{{ groups.ucp }}"
    - debug: var=ucp_instance
    - fail:
        msg: "cannot find UCP endpoint at any of {{ groups.ucp }}"
      when: ucp_instance == ".none."
    - include_tasks: includes/find_dtr.yml ping_servers="{{ groups.dtr }}"
    - debug: var=dtr_instance
    - fail:
        msg: "cannot find DTR  endpoint at any of {{ groups.dtr }}"
      when: dtr_instance == ".none."
    - include_tasks: includes/get_dtr_version.yml
    - include_tasks: includes/get_ucp_version.yml
    - debug: var=detected_dtr_version
    - debug: var=detected_ucp_version

    - fail:
        msg: "Mismatch between detected version of UCP {{ detected_ucp_version }} and documented version {{ ucp_version }}"
      when: ucp_version != detected_ucp_version 

    - fail:
        msg: "Mismatch between detected version of DTR {{ detected_dtr_version }} and documented version {{ dtr_version }}"
      when: dtr_version != detected_dtr_version 
