###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- hosts: ucp ucp_lb
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Open required ports for Grafana and Prometheus
      command: firewall-cmd --permanent --zone=public --add-port=9090/tcp --add-port=3000/tcp

    - name: Reload firewalld configuration
      command: firewall-cmd --reload

    - name: Copy monitoring files to UCP
      copy: 
        src: ../monitoring
        dest: /root
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups.ucp

    - name: Copy docker compose file
      template: src=../monitoring/docker-compose.yml.j2 dest=/root/monitoring/docker-compose.yml
      when: inventory_hostname in groups.ucp

    # not really needed but if someone makes a change to haproxy
    - name: Update haproxy.cfg on UCP Load Balancer
      template:
        src: ../templates/haproxy.cfg.ucp.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups.ucp_lb
      notify: Enable and start haproxy service

  handlers:
    - name: Enable and start haproxy service
      systemd:
        name: haproxy
        enabled: yes
        state: restarted

