ansible_user: '{{ win_username }}'
ansible_password: '{{ win_password }}'
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 250
ansible_winrm_read_timeout_sec: 300
windows_timezone: 15

networks:
  - name: '{{ vm_portgroup }}'
    ip:  "{{ ip_addr | ipaddr('address') }}"
    netmask: "{{ ip_addr | ipaddr('netmask') }}"
    gateway: "{{ gateway }}"

#  - name: 'dpgISCSI'
#    ip:  "{{ iscsi_addr | ipaddr('address') }}"
#    netmask: "{{ iscsi_addr | ipaddr('netmask') }}"

disks_specs:
#  - size_gb:  '{{ disk1_size }}'
  - size_gb:  '200'
    type: thin
    datastore: "{{ datastores | random }}"
  - size_gb: '{{ disk2_size }}'
    type: thin
    datastore: "{{ datastores | random }}"

