###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
    - name: Copy kubectl client
      copy:
        src: ../files/k8s/client/kubectl
        dest: /usr/local/bin/kubectl
        mode: 0744

    - name: Retrieve a token for the UCP API
      uri:
        url: "https://{{ ucp_instance }}.{{ domain_name }}/auth/login"
        headers:
          Content-Type: application/json
        method: POST
        status_code: 200
        body_format: json
        validate_certs: no
        body: '{"username":"{{ ucp_username }}","password":"{{ ucp_password }}"}'
      delegate_to: localhost
      register: resp
      until: resp.status == 200
      retries: 20
      delay: 5
      no_log: yes

    - name: Remember the API's token
      set_fact:
        auth_token:  "{{resp.json.auth_token}}"

    - name: Get the client bundle
      get_url:
        url: 'https://{{ ucp_instance }}.{{ domain_name }}/api/clientbundle'
        headers: 'Authorization: Bearer {{ auth_token }}'
        validate_certs: no
        force: yes
        dest: /tmp/bundle.zip
      register: resp

    - name: Create UCP Bundle dir
      file:
        path: ~/certs.{{ ucp_username }}
        state: directory

    - name: unarchive the client bundle
      unarchive:
        src: /tmp/bundle.zip
        dest: ~/certs.{{ ucp_username }}
        force: yes
