---
# This playbook will create a Docker UCP environment

- include: playbooks/create_vms.yml
- include: playbooks/config_networking.yml
#- include: playbooks/distribute_keys.yml # this step is optional; enabling it will allow for passwordless login between nodes
#- include: playbooks/config_subscription.yml
- include: playbooks/install_haproxy.yml
- include: playbooks/install_ntp.yml
- include: playbooks/install_docker.yml
- include: playbooks/install_rsyslog.yml
- include: playbooks/config_docker_lvs.yml
- include: playbooks/docker_post_config.yml
- include: playbooks/install_nfs_server.yml
- include: playbooks/install_nfs_clients.yml
- include: playbooks/install_ucp_nodes.yml
- include: playbooks/install_dtr_nodes.yml
- include: playbooks/install_worker_nodes.yml
- include: playbooks/install_logspout.yml
- include: playbooks/config_scheduler.yml
- include: playbooks/config_monitoring.yml
- include: playbooks/config_dummy_vms_for_docker_volumes_backup.yml
- include: playbooks/config_simplivity_backups.yml
