---
# This playbook will create a Docker UCP environment

- import_playbook: playbooks/create_vms.yml
- import_playbook: playbooks/config_networking.yml
- import_playbook: playbooks/resize_syspart.yml
#- import_playbook: playbooks/config_subscription.yml
- import_playbook: playbooks/loadbalancer.yml
- import_playbook: playbooks/config_ntp.yml
- import_playbook: playbooks/config_storage_driver.yml
- import_playbook: playbooks/install_docker.yml
- import_playbook: playbooks/install_rsyslog.yml
- import_playbook: playbooks/docker_post_config.yml
- import_playbook: playbooks/install_nfs_server.yml
- import_playbook: playbooks/install_nfs_clients.yml
- import_playbook: playbooks/create_main_ucp.yml
- import_playbook: playbooks/scale_ucp.yml
- import_playbook: playbooks/create_main_dtr.yml
#- import_playbook: playbooks/install_logspout.yml
#- import_playbook: playbooks/config_monitoring.yml
#- import_playbook: playbooks/splunk_demo.yml
#- import_playbook: playbooks/splunk_uf.yml
#- import_playbook: playbooks/splunk_k8s.yml
- import_playbook: playbooks/config_scheduler.yml
- import_playbook: playbooks/scale_workers.yml
- import_playbook: playbooks/scale_dtr.yml
- import_playbook: playbooks/reconfigure_dtr.yml
#- import_playbook: playbooks/install_sysdig.yml
- import_playbook: playbooks/config_dummy_vms_for_docker_volumes_backup.yml
- import_playbook: playbooks/config_simplivity_backups.yml
