###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Install NFS Server
  hosts: nfs
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  roles:
    - role: hpe.openports
      hpe_openports_ports:
        - 2049/tcp
        - 2049/udp
        - 111/tcp
        - 111/udp
        - 54302/tcp
        - 54302/udp
        - 20048/tcp
        - 20248/udp
        - 46666/tcp
        - 46666/udp
        - 42955/tcp
        - 42955/udp
        - 875/tcp
        - 875/udp
        
  tasks:

    - name: Check for partitions on disk
      parted:
        state: info
        device: "{{ disk2 }}"
        number: 1
      register: DiskInfo

    - set_fact:
        partPresent: "{{ DiskInfo.partitions[0] is defined }}"

    - name: Create partition on second disk
      parted:
        device: "{{ disk2 }}"
        number: 1
        state: present    
      when: partPresent == false

    - name: Create filesystem
      filesystem:
        fstype: xfs
        dev: "{{ disk2_part }}"
      when: partPresent == false

    - name: Create images folder
      file:
        path: "{{ images_folder }}"
        state: directory
        mode: 0777
      when: partPresent == false

    - name: Mount filesystem
      mount:
        path: "{{ images_folder }}"
        src: "{{ disk2_part }}"
        fstype: xfs
        state: mounted

#
# NFS Share for K8S PVs
#
    - name: Check for partitions on 3rd disk
      parted:
        state: info
        device: /dev/sdc
        number: 1
      register: Disk3Info

    - set_fact:
        partPresent: "{{ Disk3Info.partitions[0] is defined }}"

    - name: Create partition on 3rd disk
      parted:
        device: /dev/sdc
        number: 1
        state: present
      when: partPresent == false

    - name: Create filesystem on 3rd disk
      filesystem:
        fstype: xfs
        dev: '/dev/sdc1'
      when: partPresent == false

    - name: Create Share for K8S Persistent Volumes
      file:
        path: "{{ nfs_provisioner_server_share }}"
        state: directory
        mode: 0777
      when: partPresent == false

    - name: Mount filesystem
      mount:
        path: "{{ nfs_provisioner_server_share }}"
        src: '/dev/sdc1'
        fstype: xfs
        state: mounted

    - name: Install NFS server
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - rpcbind
        - nfs-utils

    - name: Enable and start NFS services on server
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap

    - name: Modify exports file on NFS server
      template: src=../templates/exports.j2 dest=/etc/exports
      notify: RefreshExportFS

  handlers: 

    - name: RefreshExportFS
      command: exportfs -a
