---
# This playbook will create a prometheus/grafana stack on kubernetes

- import_playbook: kube-prometheus/operator.yml
- import_playbook: kube-prometheus/kube-state-metrics.yml
- import_playbook: kube-prometheus/node-exporter.yml
- import_playbook: kube-prometheus/monitors.yml
- import_playbook: kube-prometheus/prometheus.yml
- import_playbook: kube-prometheus/grafana.yml

