###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- name: Install Splunk Universal Forwarder (Linux)
  hosts: vms
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault
    - ./includes/internal_vars.yml

  environment:
    - "{{ env }}"

  tasks:

  - block:

    - include_tasks: includes/find_ucp.yml
      vars:
        ping_servers: "{{ groups.ucp }}"

    - name: source stack specific variables
      include_vars:
        file: ../templates/splunk/{{ monitoring_stack }}/vars.yml

#
# section for the logger VM which is used to collect syslog from the ESX infrastructure and the UCP syslogs
#
    - block:

      - name: Open  ports  in the firewall
        firewalld:
          port: "{{ item }}"
          immediate: true
          permanent: true
          state: enabled
        with_items: "{{ splunk_architecture_syslog_ports }}"

      when: inventory_hostname in groups.logger

#
# Section for all Linux hosts
#
    - block:

      - name: Copy Universal forwarder for Linux Pkg
        copy:
          src: "../files/splunk/linux/{{ splunk_architecture_universal_forwarder_package }}.rpm"
          dest: /root/scripts/monitoring/

      - name: Copy Splunk Universal Forwarder for Linux start script
        template:
          src: ../templates/splunk/{{ monitoring_stack }}/start_uf_linux.sh.j2
          dest: /root/scripts/monitoring/start_uf_linux.sh
        notify: RestartLinuxSplunkUF
      - file:
          path: /root/scripts/monitoring/start_uf_linux.sh
          mode: 0744
        notify: RestartLinuxSplunkUF

      - name: Install Universal Forwarder for Linux
        yum:
          name:  /root/scripts/monitoring//{{ splunk_architecture_universal_forwarder_package }}.rpm
          state: present

      - name: Generating hash password
        command:  /opt/splunkforwarder/bin/splunk hash-passwd {{ splunk_uf_password }}
        register: splunk_uf_hash
        no_log: yes

      - name: Templating seed file 
        template:
          src: ../templates/splunk/{{ monitoring_stack }}/user-seed.conf.j2
          dest:  /opt/splunkforwarder/etc/system/local/user-seed.conf
        vars:
          splunk_uf_hash_password: "{{  splunk_uf_hash.stdout }}" 
        notify: RestartLinuxSplunkUF

      - name: Copy Splunk Universal Forwarder for Linux configuration files
        copy:
          src: "../files/splunk/linux/SPLUNK_HOME/"
          dest: "/opt/splunkforwarder/"
        notify: RestartLinuxSplunkUF

      - name: Copy Splunk Universal Forwarder for Linux Technical Add-ons on Docker hosts
        copy:
          src: "../files/splunk/linux/DOCKER_TAS/"
          dest: "/opt/splunkforwarder/"
          mode: preserve
        notify: RestartLinuxSplunkUF
        when: inventory_hostname in groups.docker

      - local_action: stat path="../templates/splunk/{{ monitoring_stack }}/outputs.conf.j2"
        register: res

      - name: Debug
        debug: var=res.stat.exists
        when: _debug is defined

      - name: Copy output.conf from template folder if present
        template:
           src: "../templates/splunk/{{ monitoring_stack }}/outputs.conf.j2"
           dest: "/opt/splunkforwarder/etc/system/local/outputs.conf"
        notify: RestartLinuxSplunkUF
        when: res.stat.exists == true

      when: inventory_hostname in groups.vms
      
# end of section of non docker hosts

    when: monitoring_stack is defined


  - debug: msg="No splunk integration wanted"
    when: monitoring_stack is not defined

  handlers:
  - name: RestartLinuxSplunkUF
    shell: /root/scripts/monitoring/start_uf_linux.sh
    args:
      chdir: /root/scripts/monitoring

#########################################################################
#
# Play 2: Install Splunk Universal Forwarder (Windows)
#
#########################################################################
- name: Install Splunk Universal Forwarder (Windows) 
  hosts: logger win_worker
  gather_facts: false
  connection: local
  become: false

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault
    - ./includes/internal_vars.yml

  environment:
    - "{{ env }}"

  tasks:

  - block:  # monitoring_stack is defined

    - include_tasks: includes/find_ucp.yml
      vars:
        ping_servers: "{{ groups.ucp }}"

    - name: source stack specific variables
      include_vars:
        file: ../templates/splunk/{{ monitoring_stack }}/vars.yml

#
# section for the logger VM which is used to collect syslog from the ESX inrastructure and the UCP syslogs
#
    - block:

      - name: Open  ports  in the firewall
        firewalld:
          port: "{{ item }}"
          immediate: true
          permanent: true
          state: enabled
        delegate_to: "{{ groups.logger[0] }}"
        become: true
        with_items: "{{ splunk_architecture_syslog_ports }}"

      when: inventory_hostname in groups.logger

#
# Section for Windows hosts
#
    - block:

      - name: Copy Universal forwarder for Windows Pkg
        win_copy:
          src: "../files/splunk/windows/{{ splunk_architecture_universal_forwarder_package }}.msi"
          dest: "./{{ splunk_architecture_universal_forwarder_package }}.msi"

      - name: Copy Splunk Universal forwarder for Windows install script
        win_template:
          src: ../templates/splunk/{{ monitoring_stack }}/install_uf_windows.ps1.j2
          dest: .\install_uf_windows.ps1

      - name: Install Universal Forwarder for Windows
        win_shell: .\install_uf_windows.ps1

      - name: Copy Splunk Universal Forwarder for Windows configuration files 
        win_copy:
          src: "../files/splunk/windows/SPLUNK_HOME/"
          dest: "c:/Program Files/SplunkUniversalForwarder/"
        notify: RestartWindowsSplunkUF

      - name: Generating hash password
        win_shell: |
          cd "C:\Program Files\SplunkUniversalForwarder\bin"
          get-location
          .\splunk.exe hash-passwd {{ splunk_uf_password }}
        register: splunk_uf_hash
        #no_log: yes

      - name: Templating seed file
        template:
          src: ../templates/splunk/{{ monitoring_stack }}/user-seed.conf.j2
          dest:  'C:\Program Files\SplunkUniversalForwarder\etc\system\local\user-seed.conf'
        vars:
          splunk_uf_hash_password: "{{  splunk_uf_hash.stdout }}"
        notify: RestartWindowsSplunkUF


      - local_action: stat path="../templates/splunk/{{ monitoring_stack }}/outputs.conf.j2"
        register: res

      - name: Debug
        debug: var=res.stat.exists
        when: _debug is defined

      - name: Copy output.conf from template folder if present
        win_template:
           src: "../templates/splunk/{{ monitoring_stack }}/outputs.conf.j2"
           dest: "c:/Program Files/SplunkUniversalForwarder/etc/system/local/outputs.conf"
        notify: RestartWindowsSplunkUF
        when: res.stat.exists == true

      - name: Start Splunk Forwarder Service
        win_service:
          name: SplunkForwarder
          state: started

      when: inventory_hostname in groups.win_worker

# end of section for Windows Hosts

    when: monitoring_stack is defined


  - debug: msg="No splunk integration wanted"
    when: monitoring_stack is not defined


  handlers:
  - name: RestartWindowsSplunkUF
    win_service:
      name: SplunkForwarder
      state: restarted
