###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- name: Install promethues with ucp metrics
  hosts: local
  connection: local
  gather_facts: false

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  environment: "{{ env }}"

  tasks:

    - debug: msg="Starting Playbook ucp-metrics-prometheus"


    - name: process templates
      template:
        src: "{{ item }}"
        dest: /tmp/{{ item | basename | regex_replace('\.j2','') }}
      with_fileglob:
      - "../templates/ucp-metrics-prometheus/*.j2"


    - include_tasks: includes/find_ucp.yml
      vars:
        ping_servers: "{{ groups.ucp }}"
    - debug: var=ucp_instance
      when: _debug is defined


    # Assume playbooks/install_client_bundle.yml has been run before this
    # Assume that ucp_instance hasn't changed in the meantime
    # - include_tasks: includes/config_client.yml

    - name: Apply yml files to  configure and install prometheus 
      shell: |
        . env.sh
        kubectl create secret generic prometheus --from-file=ca.pem --from-file=cert.pem --from-file=key.pem
        kubectl apply -f /tmp/prom_configmap.yml
        kubectl apply -f /tmp/prom_deployment.yml
        kubectl apply -f /tmp/prom_service.yml
        kubectl apply -f /tmp/graf_deployment.yml
        kubectl apply -f /tmp/graf_service.yml
        kubectl get svc prometheus
        kubectl get svc grafana
      args:
        chdir: ~/certs.{{ ucp_instance }}.{{ ucp_username }}
        executable: /usr/bin/bash
      register: ps

    - debug: var=ps.stdout_lines





